services:
  Complaingo_db:
    container_name: Complaingo_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: newpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: Complaingo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # test_db services
  test_db:
    container_name: Complaingo_test_db
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: Complaingo_test
    ports:
      - "5434:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
volumes:
  pgdata: {}
  pgdata_test: {}