services:
  crud_db:
    container_name: crud_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: newpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: crud_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}